[package]
name = "dingtalk-robot"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
hmac = "0.12"
minreq = { version = "2", features = ["https", "json-using-serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"


